export const LOAD_BOOKS = 'LOAD_BOOKS';
export const LOAD_BOOKS_PENDING = 'LOAD_BOOKS_PENDING';
export const LOAD_BOOKS_FULFILLED = 'LOAD_BOOKS_FULFILLED';
export const LOAD_BOOKS_REJECTED = 'LOAD_BOOKS_REJECTED';
