export const LOAD_DETAILS = 'LOAD_DETAILS';
export const LOAD_DETAILS_PENDING = 'LOAD_DETAILS_PENDING';
export const LOAD_DETAILS_FULFILLED = 'LOAD_DETAILS_FULFILLED';
export const LOAD_DETAILS_REJECTED = 'LOAD_DETAILS_REJECTED';

